# Generated by Django 5.2 on 2025-05-03 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testprotocol',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_protocols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testprotocol',
            name='devices',
            field=models.ManyToManyField(related_name='test_protocols', to='devices.device'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='devices.device'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='devices.testprotocol'),
        ),
        migrations.AlterUniqueTogether(
            name='testprotocol',
            unique_together={('name', 'version')},
        ),
    ]
